name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      NODE_ENV: test
    steps:
      - uses: action/checkout@v7
      - uses: action/setup-node@v7
        with:
          node-version: 22
          cache: npm
      
      - run:
          npm ci

      - name: Build and check size
        run: |
          npm run build
          du -sh dist
      
      - name: npm test
        run: npm test




      
